# Generated by Django 3.0.8 on 2020-09-01 11:27

from django.db import migrations


def combine_names(apps, schema_editor):
    old_news = apps.get_model('app_shop', 'News')
    new_news = apps.get_model('allhere_in_russia', 'News')
    new_news.objects.bulk_create(
        new_news(title=old_object.title, body=old_object.body, datetime=old_object.datetime)
        for old_object in old_news.objects.all()
    )


class Migration(migrations.Migration):
    dependencies = [
        ('allhere_in_russia', '0001_initial'),
        ('app_shop', '0014_orderlist_customer_id'),

    ]

    operations = [
        migrations.RunPython(combine_names),
    ]
