# Generated by Django 3.0.8 on 2020-09-01 12:04

from django.db import migrations


def data_transfer_shoptype(apps, schema_editor):
    old_model = apps.get_model('app_shop', 'ShopType')
    new_model = apps.get_model('allhere_in_russia', 'ShopType')
    new_model.objects.bulk_create(
        new_model(id=old_object.id,
                  title=old_object.title)
        for old_object in old_model.objects.all()
    )


def data_transfer_shops(apps, schema_editor):
    old_model = apps.get_model('app_shop', 'Shops')
    new_model = apps.get_model('allhere_in_russia', 'Shops')
    new_model.objects.bulk_create(
        new_model(name=old_object.name,
                  city=old_object.city,
                  address=old_object.address,
                  type_id=old_object.type_id,
                  description=old_object.description,
                  latitude=old_object.latitude,
                  longitude=old_object.longitude)
        for old_object in old_model.objects.all()
    )


def data_transfer_subpagesection(apps, schema_editor):
    old_model = apps.get_model('app_shop', 'SubPagesSection')
    new_model = apps.get_model('allhere_in_russia', 'SubPagesSection')
    new_model.objects.bulk_create(
        new_model(id=old_object.id,
                  title=old_object.title)
        for old_object in old_model.objects.all()
    )


def data_transfer_subpagearticle(apps, schema_editor):
    old_model = apps.get_model('app_shop', 'SubPagesArticle')
    new_model = apps.get_model('allhere_in_russia', 'SubPagesArticle')
    new_model.objects.bulk_create(
        new_model(title=old_object.title,
                  address=old_object.address,
                  section_id=old_object.section_id,
                  body=old_object.body,
                  uniq_template=old_object.uniq_template)
        for old_object in old_model.objects.all()
    )


class Migration(migrations.Migration):
    dependencies = [
        ('allhere_in_russia', '0002_auto_20200901_1427'),
        ('app_shop', '0014_orderlist_customer_id'),
    ]

    operations = [
        migrations.RunPython(data_transfer_shoptype),
        migrations.RunPython(data_transfer_shops),
        migrations.RunPython(data_transfer_subpagesection),
        migrations.RunPython(data_transfer_subpagearticle),
    ]
