# Generated by Django 3.0.8 on 2020-09-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allhere_in_russia', '0003_auto_20200901_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='city',
            field=models.CharField(choices=[('ekt', 'Екатеринбург'), ('knd', 'Краснодар'), ('mos', 'Москва'), ('nng', 'Нижний Новгород'), ('sam', 'Самара'), ('spb', 'Санкт-Петербург')], help_text='Check the city where the store is located', max_length=20),
        ),
    ]
