# Generated by Django 3.0.8 on 2020-07-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subpagesarticle',
            name='uniq_template',
            field=models.BooleanField(default=False, help_text='check if the page will use a unique HTML template'),
        ),
        migrations.AlterField(
            model_name='subpagesarticle',
            name='address',
            field=models.CharField(blank=True, help_text='Enter a url address for article, otherwise the address will be set automatically', max_length=30, null=True),
        ),
    ]
