# Generated by Django 3.0.8 on 2020-08-18 14:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter product name', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Enter a store description', null=True)),
                ('images', models.ImageField(upload_to='promotions')),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
