# Generated by Django 3.0.8 on 2020-07-30 13:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_auto_20200729_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a type of shop', max_length=30)),
            ],
            options={
                'verbose_name': 'ShopType',
                'verbose_name_plural': 'ShopsType',
            },
        ),
        migrations.AlterField(
            model_name='subpagesarticle',
            name='address',
            field=models.CharField(blank=True, help_text='Enter a url address for article, otherwise the address will be set automatically', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subpagesarticle',
            name='title',
            field=models.CharField(help_text='Enter a titles article', max_length=40),
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a titles article', max_length=40)),
                ('address', models.CharField(help_text='Enter address of shop in the format City, street, house number', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Enter a text article', null=True)),
                ('latitude', models.DecimalField(blank=True, help_text='indicates the latitude of the location on the world map', null=True)),
                ('longitude', models.DecimalField(blank=True, help_text='indicates the longitude of the location on the world map', null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content', to='app_shop.ShopType')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
