# Generated by Django 3.0.8 on 2020-08-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_auto_20200818_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='end_time',
            field=models.DateField(blank=True, help_text="Use an interactive calendar image or enter a date in the format 'YYYY-MM-DD'", null=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='start_time',
            field=models.DateField(blank=True, help_text="Use an interactive calendar image or enter a date in the format 'YYYY-MM-DD'", null=True),
        ),
    ]
