# Generated by Django 3.0.8 on 2020-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_auto_20200730_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shops',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, editable=False, help_text='indicates the latitude of the location on the world map', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, editable=False, help_text='indicates the longitude of the location on the world map', max_digits=10, null=True),
        ),
    ]
