# Generated by Django 3.0.8 on 2020-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_auto_20200818_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='for_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
