# Generated by Django 3.0.8 on 2020-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_auto_20200730_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='city',
            field=models.CharField(help_text='Enter a titles article', max_length=20),
        ),
    ]
