# Generated by Django 3.0.8 on 2020-08-04 09:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_shops_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a news titles', max_length=100)),
                ('body', tinymce.models.HTMLField(help_text='Enter a news text')),
                ('datetime', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['datetime'],
                'verbose_name': 'News',
                'verbose_name_plural': 'News'
            },
        ),
        migrations.AlterModelOptions(
            name='shops',
            options={'ordering': ['city', 'type', 'name'], 'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterField(
            model_name='shops',
            name='city',
            field=models.CharField(help_text='Enter the city where the store is located', max_length=20),
        ),
        migrations.AlterField(
            model_name='shops',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Enter a store description', null=True),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(help_text='Enter store name', max_length=40),
        ),
        migrations.AlterField(
            model_name='subpagesarticle',
            name='body',
            field=tinymce.models.HTMLField(blank=True, help_text='Enter a text article', null=True),
        ),
    ]
