# Generated by Django 3.0.8 on 2020-08-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_promotions_for_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='for_carousel',
            field=models.BooleanField(default=False, help_text='Check, if promotion should be used for the main carousel'),
        ),
    ]
