# Generated by Django 3.0.8 on 2020-08-21 10:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_auto_20200818_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder={}, null=True),
        ),
    ]
