# Generated by Django 3.0.8 on 2020-08-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_product_specifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Enter email for mailing', max_length=40)),
            ],
            options={
                'verbose_name': 'Mailing address',
                'verbose_name_plural': 'Postal addresses',
            },
        ),
    ]
