# Generated by Django 3.0.8 on 2020-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0008_subscriptionemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionemails',
            name='email',
            field=models.EmailField(help_text='Enter email for mailing', max_length=40, unique=True),
        ),
    ]
