# Generated by Django 3.0.8 on 2020-08-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0009_auto_20200822_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclassification',
            old_name='nav_name',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='promotions',
            name='for_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_class', to='app_shop.ProductClassification'),
        ),
    ]
