# Generated by Django 3.0.8 on 2020-08-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0010_auto_20200823_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='for_category',
        ),
        migrations.AddField(
            model_name='promotions',
            name='for_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='promo_class', to='app_shop.ProductClassification'),
        ),
    ]
