# Generated by Django 3.0.8 on 2020-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_auto_20200823_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField()),
                ('customer', models.CharField(blank=True, help_text='Customer', max_length=20, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone', max_length=20, null=True)),
                ('address', models.CharField(help_text='Delivery address', max_length=100)),
                ('order_creation_date', models.DateField(auto_now_add=True)),
                ('product_list', models.ManyToManyField(blank=True, null=True, related_name='for_order', to='app_shop.Product')),
            ],
        ),
    ]
