# Generated by Django 3.0.8 on 2020-08-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0011_auto_20200823_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveSmallIntegerField()),
                ('customer', models.CharField(blank=True, help_text='Customer', max_length=20, null=True)),
                ('customer_phone', models.CharField(blank=True, help_text='Customer phone', max_length=20, null=True)),
                ('address', models.CharField(help_text='Delivery address', max_length=100)),
                ('order_creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='promotions',
            name='for_category',
            field=models.ManyToManyField(related_name='promo_class', to='app_shop.ProductClassification'),
        ),
        migrations.CreateModel(
            name='ProductListForOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.OrderList')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.Product')),
            ],
        ),
        migrations.AddField(
            model_name='orderlist',
            name='product_list',
            field=models.ManyToManyField(related_name='for_order', through='app_shop.ProductListForOrder', to='app_shop.Product'),
        ),
    ]
