# Generated by Django 3.0.8 on 2020-08-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0012_orderlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='product_list',
            field=models.ManyToManyField(related_name='for_order', to='app_shop.Product'),
        ),
    ]
