# Generated by Django 3.0.8 on 2020-08-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0012_auto_20200827_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlistfororder',
            name='count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='product_list',
            field=models.ManyToManyField(through='app_shop.ProductListForOrder', to='app_shop.Product'),
        ),
        migrations.AlterModelTable(
            name='productlistfororder',
            table='app_shop_productlistfororder',
        ),
    ]
