# Generated by Django 3.0.8 on 2020-08-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0013_auto_20200826_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='order_creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='for_category',
            field=models.ManyToManyField(related_name='promo_class', to='app_shop.ProductClassification'),
        ),
    ]
