# Generated by Django 3.0.8 on 2020-09-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0014_orderlist_customer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='subpagesarticle',
            name='section',
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
        migrations.DeleteModel(
            name='ShopType',
        ),
        migrations.DeleteModel(
            name='SubPagesArticle',
        ),
        migrations.DeleteModel(
            name='SubPagesSection',
        ),
    ]
