# Generated by Django 3.0.8 on 2020-09-07 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0015_auto_20200901_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltersForClassifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter а product category', max_length=30)),
                ('type', models.CharField(choices=[('TXT', 'Фильтр по буквенному значению'), ('INT', 'Фильтр по числовому значению (MIN и MAX)'), ('CSM', 'Фильтр по чекбоксам из всех возможных значений поля')], help_text='Enter а filter type', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='products'),
        ),
        migrations.CreateModel(
            name='ClassificationFilters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.ProductClassification')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.FiltersForClassifications')),
            ],
            options={
                'db_table': 'app_shop_classificationfilters',
            },
        ),
        migrations.AddField(
            model_name='productclassification',
            name='filter',
            field=models.ManyToManyField(through='app_shop.ClassificationFilters', to='app_shop.FiltersForClassifications'),
        ),
    ]
