# Generated by Django 3.0.8 on 2020-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0016_auto_20200907_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productclassification',
            options={'ordering': ('id', 'highest_category')},
        ),
        migrations.AddField(
            model_name='filtersforclassifications',
            name='slug',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
