# Generated by Django 3.0.8 on 2020-09-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0017_auto_20200908_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filtersforclassifications',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='filtersforclassifications',
            name='slug',
        ),
        migrations.AddField(
            model_name='filtersforclassifications',
            name='priority',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
