# Generated by Django 3.0.8 on 2020-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0018_auto_20200908_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtersforclassifications',
            name='priority',
            field=models.SmallIntegerField(default=0),
        ),
    ]
