# Generated by Django 3.0.8 on 2020-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0019_auto_20200909_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Enter product price'),
        ),
    ]
