# Generated by Django 3.0.8 on 2020-09-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0020_auto_20200909_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionsForCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.ProductClassification')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.Promotions')),
            ],
            options={
                'db_table': 'app_shop_promotionsforcategory',
            },
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='for_category',
        ),
        migrations.AddField(
            model_name='promotions',
            name='for_category',
            field=models.ManyToManyField(through='app_shop.PromotionsForCategory', to='app_shop.ProductClassification'),
        ),
    ]
