# Generated by Django 3.0.8 on 2020-09-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0021_auto_20200909_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_fixed_price',
            field=models.FloatField(blank=True, help_text='Enter the price of the fixed discount', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Enter the discount percentage for this product', null=True),
        ),
    ]
