# Generated by Django 3.0.8 on 2020-09-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0023_auto_20200910_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='the_final_price',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
