# Generated by Django 3.0.8 on 2020-09-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0025_auto_20200914_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitstatistics',
            old_name='specifications',
            new_name='actions',
        ),
        migrations.AddField(
            model_name='visitstatistics',
            name='user_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitstatistics',
            name='url_address',
            field=models.CharField(max_length=200),
        ),
    ]
