# Generated by Django 3.0.8 on 2020-09-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allhere_in_russia', '0003_auto_20200901_1504'),
        ('app_shop', '0026_auto_20200914_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.Product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allhere_in_russia.Shops')),
            ],
            options={
                'db_table': 'app_shop_productquantity',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.ManyToManyField(through='app_shop.ProductQuantity', to='allhere_in_russia.Shops'),
        ),
    ]
