# Generated by Django 3.0.8 on 2020-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0027_auto_20200915_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productquantity',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
