# Generated by Django 3.0.8 on 2020-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0028_auto_20200915_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='paid',
            field=models.BooleanField(default=False, help_text='Notes whether the order has been paid'),
        ),
        migrations.AddField(
            model_name='productlistfororder',
            name='store',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
