# Generated by Django 3.0.8 on 2020-09-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0030_auto_20200915_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='obligatory',
            field=models.BooleanField(default=False, help_text='Check, if this action should always be displayed'),
        ),
    ]
