# Generated by Django 3.0.8 on 2020-09-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0032_auto_20200918_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx_among_products', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('idx_among_promotions', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shop.Promotions')),
            ],
        ),
    ]
