# Generated by Django 3.0.8 on 2020-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0033_advertising'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='obligatory',
        ),
        migrations.AddField(
            model_name='advertising',
            name='obligatory',
            field=models.BooleanField(default=False, help_text='Check, if this action should always be displayed'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='idx_among_products',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specify a position for fixing a advertising in the list of products', null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='idx_among_promotions',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specify a position for fixing a advertising in a block of promotions', null=True),
        ),
    ]
