# Generated by Django 3.0.8 on 2020-09-18 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0035_auto_20200918_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='advertising',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='promo', to='app_shop.Advertising'),
        ),
    ]
